### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bensoltoff** [julia-zhou/MACS30200proj#9]
* Your literature review is underdeveloped. I'd like to see more discussion about the process of diffusion of influence independent of the QA site studies
* Good computational element for the data collection and calculating network metrics
* Discussion of results is also a bit underwhelming. You provide 5 descriptive statistics graphs but barely discuss them. Also I still don't understand what defines the two communities in your data. At first I thought this was the critical/non-critical user distinction, but you state that each community is approximately the same size. Shouldn't there be far more non-critical users though? And a t-test is not exactly a robust hypothesis test procedure given the other approaches we covered last term

**Comment by julia-zhou** [comment]
Dear Professor Soltoff, 

Thank you for your feedback. I'm actually a little bit confused by your comments. 

For the literature review, I believe that I have provided discussion on the process of diffusion of influence independent of the QA site studies in the first part of the review. Do you mind to point out which kinds of research you felt are absent in the review?

As for the main idea of the paper, it is about observing the difference between critical users and the others. The two communities are determined by fastgreedy algorithm, which is maximizing the modularity of each community; however, these two communities are not the community of critical users and the community of non-critical users. As I described in the paper, the critical users are determined by their betweenness within their own community. The top 10% users with highest betweenness within each community are determined as critical users. In other words, whether a user is critical or not does not have anything to do with which community it is. It only depends on their importance in their own network. I guess it is only confusing for you because I only obtained two communities from the algorithm, but I have no control over it. I'm very sorry that it seems unclear for you, but I thought I had explained this approach and the reasons for this approach in the method section and in the contribution part of the literature review.

I used t-test because using logistic regression and other algorithms did not give me a effective model for predicting whether the user is critical or not. To be specific, my logistic regression model only has a R^2 as 0.01. This is understandable because there definitely are many more features that could potentially be much more effective in predicting whether a user is critical or not. Since I was aware that I would not be able to finish the feature engineering for the other features, I proposed this precise question in the beginning in this quarter, and it was approved. I thought that if I were to just answer whether there is statistically significant difference in the number of topic between the two groups, it would be sufficient to use a t-test. If you have better ideas about this, I would definitely love to hear your opinion.

I hope that I have made my ideas clearer for you even though I thought that I had tried my best to convey this idea in my paper. If you are still on campus and would be willing to meet with me, I would definitely want to do that.
